### ISSUE TITLE
Debugging broken in Powershell Tools for VS

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/poshtools-issues#77]
Breakpoints are not respected since upgrade to 5.7.8.
The scripts run fine, but does not stop at any breakpoint.
And since logging still seems not to work - for a year now? - I cannot supply with any more information.

Really beginning to consider a move to Visual Studio Code.
Too many (new) errors and very little attention to fix. I have open issues back to april with no action.
It's clearly your right to decide what to prioritize, but I'm not sure I can live with it.

**Comment by adamdriscoll** [comment]
@pju55  - Can you please let me know what version of PowerShell you are using? We had an issue where PowerShell 7.1 introduced a bug where a warning would be written when using ConvertTo-Json which caused breakpoints to fail in PoshTools. 

We have released a fix for this. 

I apologies for the lack of traction on the issues that you have opened and I will have the team triage them to see if we can get them resolved. 

If there is anything pressing, please feel free to open a ticket in our support system by emailing support@ironmansoftware.com rather than submitting issues here. We are trying to move to a more managed system to better track our customer requests.

**Comment by pju55** [comment]
@adamdriscoll - Looks like you got it pinned. I have an awful feeling that I did 2 upgrades at the time - both pwsh and poshtools. I am running 7.1.0 -and have just upgraded poshtoools - problerm gone :-)
So, my best apologies for blaming you for this.
Still, I of course would appreciate very much to see a bit progress on at least some of my issues.

A question if I may: Have you heard about problems with windows clipboard when doing copy/paste in a poshtools debug session? I cannot put my finger on exactly what triggers my problem but if copy/pasting while debugging, I will eventually see (in a clipboard widget)  that a new copy is received at the clipboard but immediately replaced with the previous copy. Effectively putting copy/paste out of business. I  have to restart Visual Studio to make copy/paste work again. Only the active VS instance is affected. 
I have not tried to report because - ahh well - thought no action would be taken anyway ;-)

Thanks for the hint on opening issues - it's noted:-)

**Comment by adamdriscoll** [comment]
> Still, I of course would appreciate very much to see a bit progress on at least some of my issues.

Of course. I'll make sure these get escalated. 

> A question if I may: Have you heard about problems with windows clipboard when doing copy/paste in a poshtools debug session? I cannot put my finger on exactly what triggers my problem but if copy/pasting while debugging, I will eventually see (in a clipboard widget) that a new copy is received at the clipboard but immediately replaced with the previous copy. Effectively putting copy/paste out of business. I have to restart Visual Studio to make copy/paste work again. Only the active VS instance is affected.
I have not tried to report because - ahh well - thought no action would be taken anyway ;-)

I haven't heard of this before but it sounds extremely annoying. I'll open an issue for this in our internal tracker. 

I'm going to close this issue as it does seem resolved. I'll follow up on some of the other issues.
